development:
  adapter: postgresql
  database: box_postgresql_development
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: box_postgresql_test
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: box_postgresql_production
  encoding: unicode
  pool: 5
  timeout: 5000
