common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: box_postgresql_development

test:
  <<: *common
  database: box_postgresql_test

production:
  <<: *common
  database: box_postgresql_production
